// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frhzajskbssoosrigepb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaHphanNrYnNzb29zcmlnZXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMwNjksImV4cCI6MjA2ODY2OTA2OX0.6dLZ_86Nm_Mc22Jr0aFlA1FZb2v6NbhTusLkfWH_63A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});